import {useState,useEffect} from 'react';
import {api,money} from './api';
import {Admin} from './features';
const date=value=>value?new Date(value).toLocaleString('en-IN'):'Not recorded yet';
export default function AdminDashboard({notify}){
 const [section,setSection]=useState('users'),[query,setQuery]=useState(''),[page,setPage]=useState(1),[data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(0);
 useEffect(()=>{if(section==='reports')return;let current=true;const load=()=>{setLoading(true);api(`/admin/dashboard?${new URLSearchParams({section,q:query,page})}`).then(value=>{if(current){setData(value);setError('');}}).catch(e=>{if(current)setError(e.message);}).finally(()=>{if(current)setLoading(false);});};const delay=setTimeout(load,250);const interval=setInterval(load,60000);return()=>{current=false;clearTimeout(delay);clearInterval(interval);};},[section,query,page,refresh]);
 const tabs=['users','listings','activity','reports'];
 return <section className="owner-dashboard"><div className="page-heading"><div><div className="eyebrow">PRIVATE · OWNER ACCESS</div><h1>Your campus, at a glance.</h1><p>See who’s here and what’s happening on Final Price?</p></div><button onClick={()=>setRefresh(v=>v+1)} disabled={loading}>Refresh</button></div>
 {error&&<p className="error" role="alert">{error}</p>}
 {data&&<><div className="owner-stats">{[['Registered users',data.summary.users],['Signed in',data.summary.signedIn],['Active in last 5 min',data.summary.online],['Active today',data.summary.activeToday],['For sale',data.summary.activeListings],['Sold',data.summary.sold],['Deleted',data.summary.deleted]].map(([label,value])=><article key={label}><span>{label}</span><strong>{value}</strong></article>)}</div><p className="owner-note">Signed in = users with a valid login session, even if their browser is closed. Active = signed-in users with the site visible recently. Counts refresh every minute.</p>
 <div className="owner-trend"><h2>Daily active users</h2><p>Last 14 days · UTC dates · signed-in visitors only</p><div className="owner-bars">{data.daily.map(day=><div key={day.day} title={`${day.day}: ${day.users} users`}><strong>{day.users}</strong><span style={{height:`${Math.max(3,day.users/Math.max(1,...data.daily.map(d=>d.users))*90)}px`}}/><small>{day.day.slice(5)}</small></div>)}</div></div></>}
 <nav className="owner-tabs" aria-label="Dashboard sections">{tabs.map(tab=><button className={tab===section?'selected':''} key={tab} onClick={()=>{setSection(tab);setPage(1);setQuery('');setData(null);setLoading(true);}}>{tab[0].toUpperCase()+tab.slice(1)}</button>)}</nav>
 {section==='reports'?<Admin notify={notify}/>:<><label className="owner-search">Search {section}<input value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}} placeholder={section==='users'?'Name or email':'Listing title or email'}/></label>
 {loading&&<p role="status">Updating dashboard…</p>}
 {data&&!loading&&<><div className="owner-table"><table><thead><tr>{(section==='users'?['User','Joined','Last active','Listings','Sold','Login / account']:section==='listings'?['Listing','Seller','Price','Status','Updated']:['Activity','User','Listing','Time']).map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{data.items.map(item=><tr key={item.id}>{section==='users'?<><td><strong>{item.name}</strong><small>{item.email}</small></td><td>{date(item.created_at)}</td><td>{date(item.last_seen)}</td><td>{item.listings}</td><td>{item.sold}</td><td>{item.status === 'active' && item.signed_in ? 'Signed in' : 'Signed out'}<small>{item.status}</small></td></>:section==='listings'?<><td><strong>{item.title}</strong></td><td>{item.name}<small>{item.email}</small></td><td>{money(item.price)}</td><td>{item.status}</td><td>{date(item.updated_at)}</td></>:<><td>{item.action}</td><td>{item.name}<small>{item.email}</small></td><td>{item.title||'—'}</td><td>{date(item.created_at)}</td></>}</tr>)}</tbody></table>{!data.items.length&&<p>No matching {section} yet.</p>}</div><div className="owner-pagination"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>{data.total} results · Page {page} of {Math.max(1,Math.ceil(data.total/25))}</span><button disabled={page*25>=data.total} onClick={()=>setPage(p=>p+1)}>Next</button></div><p className="owner-note">Visit and activity tracking started {date(data.trackingSince)}. Existing users and listings are included; earlier visits and edits cannot be reconstructed.</p></>}
 </>}
 </section>;
}
