import {useState,useEffect} from 'react';
import {Search,ArrowRight,Heart,Package,ShieldCheck} from 'lucide-react';
import {api,money} from './api';
import Modal from './Modal';
import MostViewed from './MostViewed';
export default function GuestExplore({demo=false,onExit}){
 const [section,setSection]=useState('Explore'),[sort,setSort]=useState('recommended');
 const [data,setData]=useState(null),[query,setQuery]=useState(''),[category,setCategory]=useState(''),[page,setPage]=useState(1),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState(null),[photo,setPhoto]=useState(0),[refresh,setRefresh]=useState(0),[signin,setSignin]=useState(false);
 useEffect(()=>{let current=true;const timeout=setTimeout(()=>{setLoading(true);const params=new URLSearchParams({page,q:query,sort});if(category)params.set('category',category);api(`/guest/listings?${params}`).then(value=>{if(current){setData(value);setError('');}}).catch(e=>{if(current)setError(e.message);}).finally(()=>{if(current)setLoading(false);});},200);return()=>{current=false;clearTimeout(timeout);};},[query,category,page,refresh,sort]);
 const openSpotlight=async id=>{try{const result=await api('/guest/listings?sort=popular');const item=result.items.find(item=>item.id===id);if(item){setSelected(item);setPhoto(0);}}catch(e){setError(e.message);}};
 return <><div className="campus-strip"><span>GOOD FINDS. PEOPLE YOU KNOW.</span><span>{demo?data?.university||'STUDENT DEMO':'GUEST PREVIEW'}</span></div>
 {demo?<><header className="site-header"><button className="brand" onClick={()=>setSection('Explore')}><span>Final Price<span className="wordmark-question">?</span><small>THE CAMPUS MARKETPLACE</small></span></button><nav aria-label="Main navigation">{['Explore','My listings','Saved','Messages'].map(tab=><button key={tab} className={section===tab?'selected':''} onClick={()=>setSection(tab)}>{tab}</button>)}</nav><div className="header-actions"><button className="primary sell-button" onClick={()=>setSignin(true)}>+ Sell an item</button><button className="avatar" aria-label="Demo account" onClick={()=>setSection('Account')}>D</button></div></header><div className="dev-banner">STUDENT DEMO <span>Current public listings · viewing only · no real student account</span><button onClick={onExit}>Exit demo</button></div></>:<header className="guest-header"><a className="wordmark" href="/">Final Price<span className="wordmark-question">?</span></a><a className="primary guest-signin" href="/">College sign-in <ArrowRight size={17}/></a></header>}
 <main className="workspace guest-workspace">{demo&&section!=='Explore'?<section className="empty"><h1>{section}</h1><p>{section==='Messages'?'Student conversations appear here after a buyer contacts a seller. Real conversations stay private.':section==='My listings'?'College members manage their active, sold and unavailable listings here. The demo cannot publish items.':section==='Saved'?'College members can keep their favourite finds here. The demo does not access anyone’s saved items.':'You are viewing the student demo. No college identity or private account data is attached to it.'}</p><button className="primary" onClick={()=>setSection('Explore')}>Back to Explore</button></section>:<>
 {demo?<section className="campus-hero" aria-label="Your campus marketplace"><div className="hero-copy"><div className="eyebrow">YOUR CAMPUS. YOUR PEOPLE.</div><h1>Big finds.<br/><span>Small prices.</span></h1><p>Your next favourite find could be a few doors away.</p><a href="#demo-listings">Find your next thing <ArrowRight size={18}/></a></div><MostViewed userId="public-demo" endpoint="/guest/listings?sort=popular" refresh={refresh} modalOpen={!!selected||signin} onOpen={openSpotlight} onCreate={()=>setSignin(true)}/></section>:<section className="guest-hero"><div className="eyebrow">TAKE A LOOK AROUND</div><h1>Big finds.<br/><span>Small prices.</span></h1><p>Discover what’s new at {data?.university||'our campus'}. Browse the finds, explore the photos, and see how Final Price? works.</p><div className="guest-boundary"><ShieldCheck size={18}/> Buying, selling and messaging are for verified college members.</div></section>}
 <div className="search-row" id="demo-listings"><div className="search-box"><Search size={20}/><input aria-label="Search public listings" placeholder="Search campus finds" value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}}/></div></div>
 <nav className={demo?"category-row":"owner-tabs"} aria-label="Listing categories">{['',...(data?.categories||[])].map(c=><button key={c} className={category===c?'selected':''} onClick={()=>{setCategory(c);setPage(1);}}>{c||'All finds'}</button>)}</nav>
 <div className="guest-results"><h2>{demo?'Campus listings':'Recent campus finds'} {data&&<small>({data.total})</small>}</h2><div className="guest-sort"><label>Sort by <select aria-label="Sort listings" value={sort} onChange={e=>{setSort(e.target.value);setPage(1);}}><option value="recommended">Recommended</option><option value="popular">Popular on campus</option><option value="newest">Newest first</option><option value="price-low">Price: low to high</option><option value="price-high">Price: high to low</option></select></label><button onClick={()=>setRefresh(v=>v+1)} disabled={loading}>Refresh</button></div></div>
 {error?<div className="empty" role="alert"><h2>Couldn’t load listings</h2><p>{error}</p><button onClick={()=>setRefresh(v=>v+1)}>Try again</button></div>:loading?<p role="status">Loading campus finds…</p>:<><div className="listing-grid">{data?.items.map(item=><article className="listing-card" key={item.id}><div className="card-image"><button className="image-link" aria-label={`View ${item.title}`} onClick={()=>{setSelected(item);setPhoto(0);}}>{item.images[0]?<img src={item.images[0].url} alt={item.title} loading="lazy"/>:<Package size={52}/>}</button><span className="condition">{item.condition}</span><button className="save-button" aria-label={`Sign in to save ${item.title}`} onClick={()=>setSignin(true)}><Heart size={19}/></button></div><div className="guest-card-copy"><strong>{money(item.price)}</strong><button className="guest-title" onClick={()=>{setSelected(item);setPhoto(0);}}>{item.title}</button><small>{item.category}</small></div></article>)}</div>{!data?.items.length&&<div className="empty"><h2>No matching finds yet.</h2><p>Try another category or check back soon.</p></div>}<div className="owner-pagination"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page} of {Math.max(1,Math.ceil((data?.total||0)/24))}</span><button disabled={!data?.hasMore} onClick={()=>setPage(p=>p+1)}>Next</button></div></>}
 {!demo&&<section className="guest-how"><h2>A marketplace for people on your campus.</h2><div><article><strong>1. Find something</strong><p>Browse books, gadgets, room essentials and more.</p></article><article><strong>2. Chat on Final Price?</strong><p>College members can message the seller to ask questions and agree on a price.</p></article><article><strong>3. Meet on campus</strong><p>Arrange a meetup, inspect the item and complete the exchange in person.</p></article></div><a href="/">Have a college account? Sign in to join <ArrowRight size={16}/></a></section>}</>}</main>
 {selected&&<Modal title={selected.title} onClose={()=>setSelected(null)}><div className="guest-gallery">{selected.images[photo]?<img src={selected.images[photo].url} alt={selected.title}/>:<Package size={64}/>}</div>{selected.images.length>1&&<div className="guest-thumbnails">{selected.images.map((im,i)=><button key={im.url} aria-label={`Photo ${i+1}`} aria-pressed={photo===i} onClick={()=>setPhoto(i)}><img src={im.url} alt=""/></button>)}</div>}<h2>{money(selected.price)}</h2><p>{selected.category} · {selected.condition}</p><p>Seller details and meetup locations are available to verified college members.</p><a className="primary guest-signin" href="/">Sign in to message the seller</a></Modal>}
 {signin&&<Modal title={demo?"Viewing-only student demo":"Join your campus marketplace"} onClose={()=>setSignin(false)}><p>Sign in with your official college account to save finds, message sellers and list your own items.</p><a className="primary guest-signin" href="/">College sign-in</a></Modal>}</>;
}
