import {useState,useEffect} from 'react';
import {Search,ArrowRight,Heart,Package,ShieldCheck} from 'lucide-react';
import {api,money} from './api';
import Modal from './Modal';
export default function GuestExplore(){
 const [data,setData]=useState(null),[query,setQuery]=useState(''),[category,setCategory]=useState(''),[page,setPage]=useState(1),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState(null),[photo,setPhoto]=useState(0),[refresh,setRefresh]=useState(0),[signin,setSignin]=useState(false);
 useEffect(()=>{let current=true;const timeout=setTimeout(()=>{setLoading(true);const params=new URLSearchParams({page,q:query});if(category)params.set('category',category);api(`/guest/listings?${params}`).then(value=>{if(current){setData(value);setError('');}}).catch(e=>{if(current)setError(e.message);}).finally(()=>{if(current)setLoading(false);});},200);return()=>{current=false;clearTimeout(timeout);};},[query,category,page,refresh]);
 return <><div className="campus-strip"><span>GOOD FINDS. PEOPLE YOU KNOW.</span><span>GUEST PREVIEW</span></div><header className="guest-header"><a className="wordmark" href="/">Final Price<span className="wordmark-question">?</span></a><a className="primary guest-signin" href="/">College sign-in <ArrowRight size={17}/></a></header><main className="workspace guest-workspace"><section className="guest-hero"><div className="eyebrow">TAKE A LOOK AROUND</div><h1>Big finds.<br/><span>Small prices.</span></h1><p>Discover what’s new at {data?.university||'our campus'}. Browse the finds, explore the photos, and see how Final Price? works.</p><div className="guest-boundary"><ShieldCheck size={18}/> Buying, selling and messaging are for verified college members.</div></section>
 <div className="search-row"><div className="search-box"><Search size={20}/><input aria-label="Search public listings" placeholder="Search campus finds" value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}}/></div></div>
 <nav className="owner-tabs" aria-label="Listing categories">{['',...(data?.categories||[])].map(c=><button key={c} className={category===c?'selected':''} onClick={()=>{setCategory(c);setPage(1);}}>{c||'All finds'}</button>)}</nav>
 <div className="guest-results"><h2>Recent campus finds {data&&<small>({data.total})</small>}</h2><button onClick={()=>setRefresh(v=>v+1)} disabled={loading}>Refresh</button></div>
 {error?<div className="empty" role="alert"><h2>Couldn’t load listings</h2><p>{error}</p><button onClick={()=>setRefresh(v=>v+1)}>Try again</button></div>:loading?<p role="status">Loading campus finds…</p>:<><div className="listing-grid">{data?.items.map(item=><article className="listing-card" key={item.id}><div className="card-image"><button className="image-link" aria-label={`View ${item.title}`} onClick={()=>{setSelected(item);setPhoto(0);}}>{item.images[0]?<img src={item.images[0].url} alt={item.title} loading="lazy"/>:<Package size={52}/>}</button><span className="condition">{item.condition}</span><button className="save-button" aria-label={`Sign in to save ${item.title}`} onClick={()=>setSignin(true)}><Heart size={19}/></button></div><div className="guest-card-copy"><strong>{money(item.price)}</strong><button className="guest-title" onClick={()=>{setSelected(item);setPhoto(0);}}>{item.title}</button><small>{item.category}</small></div></article>)}</div>{!data?.items.length&&<div className="empty"><h2>No matching finds yet.</h2><p>Try another category or check back soon.</p></div>}<div className="owner-pagination"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page} of {Math.max(1,Math.ceil((data?.total||0)/24))}</span><button disabled={!data?.hasMore} onClick={()=>setPage(p=>p+1)}>Next</button></div></>}
 <section className="guest-how"><h2>A marketplace for people on your campus.</h2><div><article><strong>1. Find something</strong><p>Browse books, gadgets, room essentials and more.</p></article><article><strong>2. Chat on Final Price?</strong><p>College members can message the seller to ask questions and agree on a price.</p></article><article><strong>3. Meet on campus</strong><p>Arrange a meetup, inspect the item and complete the exchange in person.</p></article></div><a href="/">Have a college account? Sign in to join <ArrowRight size={16}/></a></section></main>
 {selected&&<Modal title={selected.title} onClose={()=>setSelected(null)}><div className="guest-gallery">{selected.images[photo]?<img src={selected.images[photo].url} alt={selected.title}/>:<Package size={64}/>}</div>{selected.images.length>1&&<div className="guest-thumbnails">{selected.images.map((im,i)=><button key={im.url} aria-label={`Photo ${i+1}`} aria-pressed={photo===i} onClick={()=>setPhoto(i)}><img src={im.url} alt=""/></button>)}</div>}<h2>{money(selected.price)}</h2><p>{selected.category} · {selected.condition}</p><p>Seller details and meetup locations are available to verified college members.</p><a className="primary guest-signin" href="/">Sign in to message the seller</a></Modal>}
 {signin&&<Modal title="Join your campus marketplace" onClose={()=>setSignin(false)}><p>Sign in with your official college account to save finds, message sellers and list your own items.</p><a className="primary guest-signin" href="/">College sign-in</a></Modal>}</>;
}
